# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

likelihood <- function(k, alpha, intercept, sf, betas, cond) {
    .Call('xtail_likelihood', PACKAGE = 'xtail', k, alpha, intercept, sf, betas, cond)
}

fastSum <- function(x1, y1) {
    .Call('xtail_fastSum', PACKAGE = 'xtail', x1, y1)
}

boundFC <- function(k1, alpha1, intercept1, sf1, FC1, cond1, k2, alpha2, intercept2, sf2, FC2, cond2, stepFC, toleration) {
    .Call('xtail_boundFC', PACKAGE = 'xtail', k1, alpha1, intercept1, sf1, FC1, cond1, k2, alpha2, intercept2, sf2, FC2, cond2, stepFC, toleration)
}

posterior <- function(k, alpha, intercept, sf, priorSigma, betas, cond) {
    .Call('xtail_posterior', PACKAGE = 'xtail', k, alpha, intercept, sf, priorSigma, betas, cond)
}

overlapCoef <- function(a, b) {
    .Call('xtail_overlapCoef', PACKAGE = 'xtail', a, b)
}

xtail_test <- function(k1, k2, ints1, ints2, log2FC_1, log2FC_2, priorSigma1, priorSigma2, disper1, disper2, sf1, sf2, cond1, cond2, bin) {
    .Call('xtail_xtail_test', PACKAGE = 'xtail', k1, k2, ints1, ints2, log2FC_1, log2FC_2, priorSigma1, priorSigma2, disper1, disper2, sf1, sf2, cond1, cond2, bin)
}

