# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitBeta2 <- function(ySEXP, xSEXP, nfSEXP, alpha_hatSEXP, contrastSEXP, beta_matSEXP, lambdaSEXP, tolSEXP, maxitSEXP, useQRSEXP) {
    .Call('xtail_fitBeta2', PACKAGE = 'xtail', ySEXP, xSEXP, nfSEXP, alpha_hatSEXP, contrastSEXP, beta_matSEXP, lambdaSEXP, tolSEXP, maxitSEXP, useQRSEXP)
}

probDensity <- function(k, alpha, intercept, sf, betas, cond) {
    .Call('xtail_probDensity', PACKAGE = 'xtail', k, alpha, intercept, sf, betas, cond)
}

probMatrix <- function(x, y, side) {
    .Call('xtail_probMatrix', PACKAGE = 'xtail', x, y, side)
}

probMatrixCI <- function(x, y, side, ci) {
    .Call('xtail_probMatrixCI', PACKAGE = 'xtail', x, y, side, ci)
}

boundFC <- function(k1, alpha1, intercept1, sf1, FC1, cond1, k2, alpha2, intercept2, sf2, FC2, cond2, stepFC, toleration) {
    .Call('xtail_boundFC', PACKAGE = 'xtail', k1, alpha1, intercept1, sf1, FC1, cond1, k2, alpha2, intercept2, sf2, FC2, cond2, stepFC, toleration)
}

xtail_test <- function(k1, k2, ints1, ints2, log2FC_1, log2FC_2, disper1, disper2, sf1, sf2, cond1, cond2, bin, ci) {
    .Call('xtail_xtail_test', PACKAGE = 'xtail', k1, k2, ints1, ints2, log2FC_1, log2FC_2, disper1, disper2, sf1, sf2, cond1, cond2, bin, ci)
}

