%\VignetteIndexEntry{xtail}
%\VignetteDepends{xtail}
%\VignetteKeywords{xtail}
%\VignettePackage{xtail}
%\VignetteEngine{knitr::knitr}

% To compile this document
% library('knitr');rm(list=ls());knit('xtail.Rnw')

\documentclass[a4paper]{article}
\newcommand{\lowtilde}{\raise.17ex\hbox{$\scriptstyle\mathtt{\sim}$}}
<<knitr, echo=FALSE>>=
library("knitr")
@

\title{Genome-wide assessment of differential translations with ribosome profiling data \\-- the xtail package}
\author{Zhengtao Xiao$^{1-3}$, Qin Zou$^{1,3}$, Yu Liu$^{1-3}$, and Xuerui Yang$^{1-3}$
\\[1em] \small{$^{1}$MOE Key Laboratory of Bioinformatics, }
\\ \small{$^{2}$Tsinghua-Peking Joint Center for Life Sciences,}
\\ \small{$^{3}$School of Life Sciences, Tsinghua University, Beijing 100084, China.}}

<<<style,eval=TRUE,echo=FALSE,results='asis'>>=
BiocStyle::latex()
@


\begin{document}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(
concordance=TRUE
)
@

\maketitle
\section{Introduction}

This package is for identifing genes undergoing differential translation with ribosome profiling data. Xtail stats with a simple assumption that if a gene undergoing translational dyresgulation under certain exprimental or physiological condition, the change of its RPF abundance should be discoordinated with that of mRNA expression. Therefore, Xtail first estimates fold changes of RPF and mRNA across two conditions, separately, to quantify the magnitude of differential translation. In a parallel process, Xtail also  estimate ratios of RPF over mRNA, in two conditions, to assess the differential translation. This strategy avoid fase disvoeries of differential translation due to extremely larger expression change in mRNA or RPF between two conditions.

Xtail  consists of three major steps: (1) statistical modeling of ribosome profiling data using negative binomial distribution model (NB), (2) estabilishment of probability distributions for fold changes of mRNA or RPF (or RPF-to mRNA ratios), and (3) evaluation of statistical significance and magnitude of differential translations. The differential translation of each gene is evaluated by two parallel, one is difference of log2 fold change of mRNA and RPF across two condition, another one is difference of log2 ratio of RPF over mRNA between two conditions. The more conserved one was selected as the final assement of differential translation.

As default, the package adapt the strategy of DESeq2 [1] to normalize read counts of mRNA and RPF in all samples, and fit NB distributions with dispersions $\alpha$ and $\mu$.

This guide provides step-by-step instructions on how to load data, how to excute the package and how to interpret output.
\newpage
\section{Data Preparation}

As input, the \verb'Xtail' package uses read counts of RPF and mRNA, in the form of rectangular table of values. The rows and the columns of the table correspond the genes and samples. Each cell in the \textsl{g-th} row and the \textsl{i-th} columns is the count number of reads mapped to gene \textsl{g} in sample \textsl{i}. The mRNA count data and RPF count data are stored in two text files.We can read them in using \textbf{R}'s standard function. For example,

<<readData,eval=FALSE>>=
mrna <- read.table("mRNA_counts.txt", header=TRUE, row.names=1)
rpf <- read.table("RPF_counts.txt", header=TRUE, row.names=1)
@

Here, header=TRUE indicates that the first line contains columns names and row.names=1 means that the first column should be used as row names (gene names or gene ID).

Xtail takes in raw read counts of RPF and mRNA, and performs median-of-ratios normalization by default. This normalization method is also recommend by Reddy R. [2] after they evaluates for different normalization methods. Alternatively, users can provide normalized read counts and skip the built-in normalization in Xtail.

In this vignette, we selected a published ribosome profiling dataset from human prostate cancer cell PC3 after mTOR signaling inhibition with PP242 [3]. This dataset consisting of 11391 genes from two conditions ("treatment" vs. "control") with each condition having two replicates.

\section{An Example}

Here we perform an analysis on the ribosome profiling data described above. First we load the library and data.

<<begain,results="hold",message=FALSE>>=
library(xtail)
data(xtaildata)
@


Next we can have a look at the first five lines of the mRNA (\verb'mrna') and RPF (\verb'rpf') elements of \verb'xtaildata'.

<<>>=
mrna <- xtaildata$mrna
rpf <- xtaildata$rpf
head(mrna,5)
head(rpf,5)
@


We assign condition labels corresponding to the columns of the mRNA and RPF inputs.

<<>>=
condition <- c("control","control","treat","treat")
@


Next, we run the main function, \verb'xtail()'. By default, the second condition (here is "treat") would be compared against the first condition (here is "control"). Those genes with the minimum average expression of mRNA counts and RPF counts acrossing all conditions larger than 1 are used (can be changed by set \verb'minMeanCount'). All the available CPU cores are used for running program. The argument \verb'bins' is the number of bins used for calculate the probability densities of log2FC and log2R. This paramater will determine how accurate the final pvalue. Here, in order to keep the run-time of this vignette small, we will set \verb'bins' to '1000'.

<<>>=
test.results <- xtail(mrna,rpf,condition,bins=1000)
@


Now we can examine the first five lines of the results produced by the \verb'xtail()' run.

<<inspectData,echo=TRUE>>=
head(test.results,5)
@


The elements \verb'log2FC_TE_v1', \verb'OVL_v1', and \verb'pvalue_v1' are log2 fold changes of TE, overlap coefficience, and pvalues, by comparson with mRNA and RPF log2FC distributions. The \verb'log2FC_TE_v2', \verb'OVL_v2', and \verb'pvalue_v2' are derived from log2R distributions between two conditions. The \verb'OVL_final', \verb'pvalue_final' and \verb'log2FC_TE_final' are the final overlap coefficience, pvalues, and log2 fold of change. Smaller OVL suggest uncoordinated changes of RPF and mRNA across different coditions, supporting differential translations. pvalue tells us the statistical significance of differential translations. The \verb'pvalue.adjust' is the estimated false discovery rate corresponding to the \verb'pvalue_final'. The \verb'CI' is the credible interval of \verb'log2FC_TE_final' (95\% by default), and which could be changed by setting \verb'ci' in \verb'xtail' function.

Finally, the plain-text file of the results can be exported using the base \textbf{R} functions \textsl{write.csv} or \textsl{write.table}.

<<writeResult,eval=FALSE>>=
write.table(test.results,"test_results.txt",quote=F,sep="\t")
@


\section*{Session Info}

<<sessInfo>>=
sessionInfo()
@



\begin{thebibliography}{99}
\bibitem{DESeq2}
Love MI, Huber W, Anders S: \textsl{Moderated Estimation of Fold Change and Dispersion for RNA-Seq Data with DESeq2}. Genome Biology 2014, 15:550.
A Comparison of Methods: Normalizing High-Throughput RNA Sequencing Data.
\bibitem{Reddy}
Reddy R: \textsl{A Comparison of Methods: Normalizing High-Throughput RNA Sequencing Data. Cold Spring Harbor Labs Journals}. bioRxiv 2015:1???9.
\bibitem{PC3}
Hsieh AC, Liu Y, Edlind MP, et al.: \textsl{The translational landscape of mTOR signaling steers cancer initiation and metastasis}. Nature 2012, 485:55???61.
\end{thebibliography}

\end{document}

